apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd          # ← Argo CD usually lives in argocd namespace
spec:
  project: default

  source:
    repoURL: https://charts.jenkins.io
    chart: jenkins
    targetRevision: 5.x.x     # or "*" / "latest" / a fixed version like "5.0.0"

    # Intentionally empty → no customization, pure defaults
    helm:
      # You can optionally add releaseName if you want something other than "jenkins"
      # releaseName: my-jenkins

  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins        # will be created if missing

  syncPolicy:
    automated:                # optional – comment out if you want manual syncs
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true  # auto-create namespace if missing
