apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.jenkins.io
    chart: jenkins
    targetRevision: 5.x.x          # or a fixed version like 5.0.0 or *
    helm:
      values: |
        controller:
          serviceType: LoadBalancer
          servicePort: 8080
        persistence:
          enabled: true
          size: 8Gi
          # storageClass: "standard"   # ← set if needed (leave empty to use cluster default)

  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
