# cloud_user-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cloud-user-binding
  namespace: clouduser
subjects:
- kind: User
  name: cloud_user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: cloud-user-role
  apiGroup: rbac.authorization.k8s.io
